name: BetterDo API

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v2
            - run: NVMRC=$(cat .nvmrc)
            - uses: actions/setup-node@v2
              with:
                  node-version: ${NVMRC}
            - run: echo ${NVMRC}
            - run: node --version
            - run: npm install
            - run: npm test
