name: BetterDo API

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v2
            - name: Read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v1
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
            - name: Install modules
              run: npm install
            - name: Run tests
              run: npm test
